version: '3.9'

networks:
  faraway-net:

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    networks:
      - faraway-net
    ports:
      - "8088:8088"
    extra_hosts:
      - "host.docker.internal:host-gateway"
